TrackIT/Models/Issue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace TrackIT.Models
{
    public class Issue
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Summary { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public int Priority { get; set; } //1-Low, 2-Normal, 3-High, 4-Very High
        public int Status { get; set; } //1-Waiting, 2-Open, 3-In Progress, 4-Closed, 5-Resolved
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? CloseDate { get; set; }
    }
}

TrackIT/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TrackIT.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public DateTime StartDate { get; set; }
    }
}

TrackIT/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace TrackIT.Controllers
{
    public class IssueController : BaseController
    {
        private TrackIT.Models.IFileStore _fileStore = new TrackIT.Models.DiskFileStore();

        //View a gerek var mı? 
        //Sonradan edit etmeye hakkı olmayan kullanıcıların sadece view etme gibi bir secenegi olabilir.
        public ActionResult View(int id)
        {
            var issue = db.Issues.Single(i => i.Id == id);
            var priorityTypes = db.PriorityTypes;
            ViewBag.PriorityTypes = priorityTypes;
            var statusTypes = db.StatusTypes;
            ViewBag.StatusTypes = statusTypes;

            return View(issue);
        }

        public ActionResult Create(int id) //Project Id
        {
            var projects = db.Projects;
            ViewBag.Projects = projects;
            var priorityTypes = db.PriorityTypes;
            ViewBag.PriorityTypes = priorityTypes;
            var statusTypes = db.StatusTypes;
            ViewBag.StatusTypes = statusTypes;
            var currentProject = db.Projects.Single(p => p.Id == id);
            ViewBag.CurrentProject = currentProject;

            return View(new Models.Issue() { ProjectId = id });
        }

        [HttpPost]
        public ActionResult Create(Models.Issue issue) //Project Id
        {
            issue.CreateDate = DateTime.Now;
            issue.Status = 1; //Default, Waiting
            db.Issues.Add(issue);
            db.SaveChanges();

            return RedirectToAction("View", "Project", new { id = issue.ProjectId });
        }

        public ActionResult Edit(int id)
        {
            var issue = db.Issues.Single(i => i.Id == id);
            var projects = db.Projects;
            ViewBag.Projects = projects;
            var priorityTypes = db.PriorityTypes;
            ViewBag.PriorityTypes = priorityTypes;
            var statusTypes = db.StatusTypes;
            ViewBag.StatusTypes = statusTypes;
            var currentProject = db.Projects.Single(p => p.Id == issue.ProjectId);
            ViewBag.CurrentProject = currentProject;
            var issueFileList = db.Files.Where(f => f.IssueId == id);
            ViewBag.IssueFileList = issueFileList;

            return View(issue);
        }

        [HttpPost]
        public ActionResult Edit(Models.Issue issue)
        {
            if (ModelState.IsValid)
            {
                issue.UpdateDate = DateTime.Now;
                if (issue.Status == 3 || issue.Status == 4) //Close yada Resolve
                    issue.CloseDate = DateTime.Now;
                db.Entry(issue).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("View", "Project", new { id = issue.ProjectId });
            }

            return RedirectToAction("Edit", new { id = issue.Id });
        }

        public string AsyncUpload(int id)
        {
            string fileName = string.Empty;
            //TODO: Upload edilen dosyayı, dbde issue ile ilişkilendir. Mapping kısaca.. Buradan dosya ismi dönüyor. (Yalnızca ismi. Path dönmüyor.)
            try
            {
                fileName = _fileStore.SaveUploadedFile(Request.Files[0]);
            }
            catch (Exception ex)
            {

                throw;
            }
            finally
            {
                db.Files.Add(new Models.File() { IssueId = id, Name = fileName, UploadDate = DateTime.Now });
                db.SaveChanges();
                //Dosya ismini Kaydet
            }

            return fileName;
        }

        //public ActionResult AsyncUpload(int id)
        //{
        //    string fileName = string.Empty;
        //    IEnumerable<Models.File> issueFileList;

        //    //TODO: Upload edilen dosyayı, dbde issue ile ilişkilendir. Mapping kısaca.. Buradan dosya ismi dönüyor. (Yalnızca ismi. Path dönmüyor.)
        //    try
        //    {
        //        fileName = _fileStore.SaveUploadedFile(Request.Files[0]);
        //    }
        //    catch (Exception ex)
        //    {

        //        throw;
        //    }
        //    finally
        //    {
        //        db.Files.Add(new Models.File() { IssueId = id, Name = fileName, UploadDate = DateTime.Now });
        //        db.SaveChanges();
        //        issueFileList = db.Files.Where(f => f.IssueId == id);
        //        //Dosya ismini Kaydet
        //    }

        //    return PartialView("_IssueFileList", issueFileList);
        //}
    }
}

TrackIT/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrackIT.Controllers
{
    public class ProjectController : BaseController
    {
        //
        // GET: /Project/

        public ActionResult View(int id, int? status)
        {
            var project = db.Projects.Single(p => p.Id == id);
            ViewBag.Project = project;
            var issues = db.Issues.Where(i => i.ProjectId == id && (status == null || i.Status == status));
            ViewBag.Issues = issues;
            var priorityTypes = db.PriorityTypes;
            ViewBag.PriorityTypes = priorityTypes;
            var statusTypes = db.StatusTypes;
            ViewBag.StatusTypes = statusTypes;
            ViewBag.CurrentStatus = status;

            return View(project);
        }

        //public ActionResult ViewIssues(int id, int? status)
        //{
        //    var project = db.Projects.Single(p => p.Id == id);
        //    var issues = db.Issues.Where(i => i.ProjectId == id && status == null || i.Status == status);

        //    return View(project);
        //}

        public ActionResult Create()
        {
            return View(new Models.Project());
        }

        [HttpPost]
        public ActionResult Create(Models.Project newProject)
        {
            newProject.StartDate = DateTime.Now;
            db.Projects.Add(newProject);
            db.SaveChanges();

            return RedirectToAction("View", "Project", new { id = newProject.Id });
        }

        public ActionResult Edit(int id)
        {
            var project = db.Projects.Single(p => p.Id == id);

            return View(project);
        }

        [HttpPost]
        public ActionResult Edit(Models.Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = System.Data.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Edit", "Project", new { id = project.Id });
        }
    }
}

TrackIT/Views/Project/Create.cshtml
@model TrackIT.Models.Project
@{
    ViewBag.Title = "Create";
}
<div class="grid_12">
    <h2>
        Create</h2>
</div>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="grid_10">
        <div class="box ui-corner-all">
            <h1>
                Create New Project</h1>
            <label>
                <span>Project Name:</span>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </label>
            <label>
                <span>Short Name:</span>
                @Html.EditorFor(model => model.ShortName)
                @Html.ValidationMessageFor(model => model.ShortName)
            </label>
            <label>
                <span></span>
                <input type="submit" value="Create" class="button" /></label>
        </div>
    </div>
}

TrackIT/Views/Project/Edit.cshtml
@model TrackIT.Models.Project
@{
    ViewBag.Title = "Edit";
}
<div class="grid_12">
    <h2>
        Edit Project</h2>
</div>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="grid_2">
        Project Name:</div>
    <div class="grid_10">@Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)</div>
    <div class="grid_2">
        Short Name:</div>
    <div class="grid_10">@Html.EditorFor(model => model.ShortName)
        @Html.ValidationMessageFor(model => model.ShortName)</div>
    <div class="grid_2">
        Start Date:</div>
    <div class="grid_10">@Html.EditorFor(model => model.StartDate)
        @Html.ValidationMessageFor(model => model.StartDate)</div>
    <div class="grid_12">
        <p>
            <input type="submit" value="Save" />
        </p>
    </div>
}

TrackIT/Views/Project/View.cshtml
@model TrackIT.Models.Project
@{
    ViewBag.Title = "View";
}
@Html.Partial("_ProjectDetails", (TrackIT.Models.Project)@Model)
@Html.Partial("_IssueFilter", (TrackIT.Models.Project)@Model)
@*<div class="grid_10">
    @Html.Partial("_IssueChart")*@
    @Html.Partial("_Issues", (IEnumerable<TrackIT.Models.Issue>)ViewBag.Issues)
@*</div>*@

TrackIT/Views/Project/_IssueChart.cshtml
<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

    // Load the Visualization API and the piechart package.
    google.load('visualization', '1.0', { 'packages': ['corechart'] });

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Mushrooms', 3],
          ['Onions', 1],
          ['Olives', 1],
          ['Zucchini', 1],
          ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = { 'title': 'How Much Pizza I Ate Last Night',
            'width': 400,
            'height': 300
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>
<!--Div that will hold the pie chart-->
    <div id="chart_div">
    </div>

TrackIT/Views/Project/_Issues.cshtml
@model IEnumerable<TrackIT.Models.Issue>
@{
    string issueClassName = "";
}
<div class="grid_10">
    <b>
        @{
            string statusTypeFilter = "All";
            if (ViewBag.CurrentStatus != null)
            {
                statusTypeFilter = ((TrackIT.Models.StatusType)((IEnumerable<TrackIT.Models.StatusType>)ViewBag.StatusTypes).SingleOrDefault(s => s.Id == ViewBag.CurrentStatus)).Name;
            }
        }
        @statusTypeFilter Issues </b>
    <div class="issueheader">
        <div class="issueheader-id issue-table-left">
            Id
        </div>
        <div class="issueheader-summary issue-table-in">
            Summary
        </div>
        <div class="issueheader-priority issue-table-in">
            Priority
        </div>
        <div class="issueheader-status issue-table-in">
            Status
        </div>
        <div class="issueheader-duedate issue-table-right">
            Due Date
        </div>
    </div>
    <div class="clear">
    </div>
    @foreach (var item in Model)
    {
        if (item.Status == 1)
        {
            issueClassName = "issue-waiting";
        }
        if (item.Status == 2)
        {
            issueClassName = "issue-inprogress";
        }
        if (item.Status == 3)
        {
            issueClassName = "issue-closed";
        }
        if (item.Status == 4)
        {
            issueClassName = "issue-resolved";
        }
        <div class="issuelist @issueClassName">
            <div class="issueheader-id issue-table-left">
                @item.Id
            </div>
            <div class="issueheader-summary issue-table-in">
                @Html.ActionLink(item.Summary, "Edit", "Issue", new { id = item.Id }, null)
            </div>
            <div class="issueheader-priority issue-table-in">
                @{
           var priorityName = ((TrackIT.Models.PriorityType)((IEnumerable<TrackIT.Models.PriorityType>)ViewBag.PriorityTypes).SingleOrDefault(p => p.Id == item.Priority)).Name;
                }
                @priorityName
            </div>
            <div class="issueheader-status issue-table-in">
                @{
           var statusName = ((TrackIT.Models.StatusType)((IEnumerable<TrackIT.Models.StatusType>)ViewBag.StatusTypes).SingleOrDefault(s => s.Id == item.Status)).Name;
                }
                @statusName
            </div>
            <div class="issueheader-duedate issue-table-right">
                @(item.DueDate.HasValue ? string.Format("{0:dd/MM/yyyy}", item.DueDate) : "-")
            </div>
        </div>
    }
</div>